edition = "2021"
tab_spaces = 2
fn_args_layout = "Vertical"
force_multiline_blocks = true
max_width = 90
reorder_imports = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
single_line_if_else_max_width = 70
