[build]

[target.x86_64-unknown-linux-gnu]
#linker = "clang"
#rustflags = ["-C", "link-arg=-fuse-ld=lld"]
linker = "clang-16"
rustflags = ["-C", "link-arg=-fuse-ld=lld-16", "--verbose"]
#rustflags = ["-C", "link-arg=-fuse-ld=mold"]
